version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-app
    container_name: node-app
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0  
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USERNAME}", "-p${DB_PASSWORD}"]
      timeout: 20s
      retries: 10

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
